<a href="https://colab.research.google.com/github/KimSiGyum/Python/blob/main/3O4O5_%EA%B9%80%EC%8B%9C%EA%B2%B8_%EC%9D%B4%EB%AF%B8%EC%A7%80_%EB%8D%B0%EC%9D%B4%ED%84%B0(%EA%B8%B0%EC%B4%88)(%ED%95%99%EC%83%9D%EC%9A%A9).ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

#**🖼️ 이미지 데이터 (기초)**
- 실습용 이미지 파일 1 : [three.png](https://drive.google.com/file/d/1hXhjadDpUakY_BaGpeM6FdB5qFHN1UYv/view?usp=sharing)
- 실습용 이미지 파일 2 : [colors.png](https://drive.google.com/file/d/1mNhvtGdgKo7qkVEtg5fjsCgj4QzxK2VA/view?usp=sharing)
---


###**▶ 컴퓨터에서 이미지를 표현하는 방법**

이미지 데이터는 이미지를 매우 세밀한 격자로 나누고 각 칸의 색상 값을 매겨 표현한다.
- 픽셀(pixel)은 이미지를 나눈 격자에서 특정 위치에 배치됨 (위치 정보를 가짐)
- 픽셀은 해당 위치의 색을 표현함 (색상 정보를 가짐)
- 색상 정보는 숫자 값으로 표현되기 때문에 <u>수학적 방법을 통해 이미지를 처리</u>할 수 있음

**▷ <u>필요한 라이브러리 임포트</u>**
>실습을 위해 아래 코드를 우선 실행하자. (※ OpenCV 참고 : https://docs.opencv.org/4.x/d6/d00/tutorial_py_root.html)

In [ ]:
import cv2 # OpenCV 파이썬 라이브러리 가져오기
from google.colab.patches import cv2_imshow # 코랩에서 웹브라우저에 이미지를 출력하기 위해 사용

---
####**01. 흑백사진의 표현 (grayscale image)**
- 흑백사진에서 픽셀은 0~255 사이의 정수 값을 가짐
- 이 값은 검정(0)~흰색(255) 사이의 명암 값을 의미함

> <img src='https://drive.google.com/uc?id=1p4dji5VUHBPxJKb29a_6zOACouVRXRku' width=1500>

**▷ <u>흑백이미지 가져오기</u>**
>(1) 코랩 서버에 three.png를 업로드하고 OpenCV를 이용해 흑백 이미지를 읽어오자.

In [ ]:
gray = cv2.imread('three.png', cv2.IMREAD_GRAYSCALE) # 이미지를 회색조로 읽어오기

**▷ <u>흑백이미지 출력하기</u>**
>(2) cv2_imshow()를 이용해 이미지를 출력해보자.

In [ ]:
cv2_imshow(gray) # 이미지 출력하기

**▷ <u>흑백이미지 살펴보기</u>**
>(3) 읽어온 이미지 gray에 대해 아래의 출력 결과가 무엇을 의미하지는 주석으로 적어보자.

In [ ]:
print(type(gray)) #이미지 gray의 타입이 넘파이 배열이다

<class 'numpy.ndarray'>


In [ ]:
print(gray.ndim) #gray의 차원 수 가 2차원이다

2


In [ ]:
print(gray.shape) #gray의 형태가 가로 28픽셀, 세로 28픽셀이다

(28, 28)


In [ ]:
print(gray.size) #gray의 픽셀 수가 784이디

784


In [ ]:
print(gray.dtype) #gray의 픽셀 값이 부호없는 8비트 정수이다 (0 ~ 255)

uint8


>(4) 이미지를 픽셀의 배열 상태 그대로 출력해보자.

In [ ]:
print(gray)

[[255 255 255 255 255 255 255 255 255 255 255 255 255 255 255 255 255 255
  255 255 255 255 255 255 255 255 255 255]
 [255 255 255 255 255 255 255 255 255 255 255 255 255 255 255 255 255 255
  255 255 255 255 255 255 255 255 255 255]
 [255 255 255 255 255 255 255 255 255 255 255 255 255 255 255 255 255 255
  255 255 255 255 255 255 255 255 255 255]
 [255 255 255 255 255 255 255 255 255 255 255 255 255 255 255 255 255 255
  255 255 255 255 255 255 255 255 255 255]
 [255 255 255 255 255 255 255 255 255 255 255 255 255 255 255 255 255 255
  255 255 255 255 255 255 255 255 255 255]
 [255 255 255 255 255 255 255 255 218  37   1   1   1   0 141 163 255 255
  255 255 255 255 255 255 255 255 255 255]
 [255 255 255 255 255 255 255 138  35   2   2   2   2   2   2   7 152 255
  255 255 255 255 255 255 255 255 255 255]
 [255 255 255 255 255 255 255 109   2   2   2   2   2   2   2   2 126 255
  255 255 255 255 255 255 255 255 255 255]
 [255 255 255 255 255 255 255 109  93  95 179 248 248 168  10   

>(5) 28*28 행렬(matrix) 형태로 픽셀 값을 출력해보자.

In [ ]:
for i in range(28):
  for j in range(28):
    print("%3d" %gray[i, j], end="") # 값 출력
  print() # 줄바꿈

255255255255255255255255255255255255255255255255255255255255255255255255255255255255
255255255255255255255255255255255255255255255255255255255255255255255255255255255255
255255255255255255255255255255255255255255255255255255255255255255255255255255255255
255255255255255255255255255255255255255255255255255255255255255255255255255255255255
255255255255255255255255255255255255255255255255255255255255255255255255255255255255
255255255255255255255255218 37  1  1  1  0141163255255255255255255255255255255255255
255255255255255255255138 35  2  2  2  2  2  2  7152255255255255255255255255255255255
255255255255255255255109  2  2  2  2  2  2  2  2126255255255255255255255255255255255
255255255255255255255109 93 95179248248168 10  2126255255255255255255255255255255255
255255255255255255255220253255255255250136  7  6144255255255255255255255255255255255
255255255255255255255255255255255255139  2  2110255255255255255255255255255255255255
255255255255255255255255255255255 29  6  2  212725525525525525525

---
####**02. 컬러사진의 표현 (colored image)**
- 컬러사진에서 픽셀은 Red 채널, Green 채널, Blue 채널 (RGB) 값을 가짐
- R, G, B는 빨간빛, 초록빛, 파란빛의 강도를 나타내며, 각 빛의 강도는 약(0)~강(255) 사이의 값으로 표현
- R, G, B 세 가지 값의 조합에 의해 약 1680만 가지의 색상을 표현

>**※ 빛의 삼원색 ※**<br>
<img src='https://drive.google.com/uc?id=1585hblBSI18Mmf7CKqAg0mnIZVsV7JQT' width=250>



따라서 컬러사진은 아래와 같이 3개의 채널이 혼합되어 표현된다.
> <img src='https://drive.google.com/uc?id=1aJjPZUTUX3y8ZuMjzQwGcLJOXC7GHf-i' width=1500>


**▷ <u>컬러이미지 가져오기</u>**
>(1) 코랩 서버에 colors.png를 업로드하고 OpenCV를 이용해 컬러 이미지를 읽어오자.

In [ ]:
color = cv2.imread('colors.png') # 이미지를 읽어오기

**▷ <u>컬러이미지 출력하기</u>**
>(2) cv2_imshow()를 이용해 이미지를 출력해보자.

In [ ]:
cv2_imshow(color) # 이미지 출력하기

**▷ <u>컬러이미지 살펴보기</u>**
>(3) 읽어온 이미지 color에 대해 아래의 출력 결과가 무엇을 의미하지는 주석으로 적어보자.

In [ ]:
print(type(color)) #color가 넘파이 배열이다.

<class 'numpy.ndarray'>


In [ ]:
print(color.ndim) #color가 3차원 배열이다.

3


In [ ]:
print(color.shape) #color는 값을 저장하는 1차원 배열이 가로 28, 세로 28개로 구성되어 컬러이미지를 구성한다.

(28, 28, 3)


In [ ]:
print(color.size) #값의 수 (픽셀 수 X)

2352


In [ ]:
print(color.dtype)

uint8


>(4) 이미지를 픽셀의 배열 상태 그대로 출력해보자.

In [ ]:
print(color)

[[[  0   0 255]
  [  0   0 255]
  [  0   0 255]
  ...
  [  0 255 255]
  [  0 255 255]
  [  0 255 255]]

 [[  0   0 255]
  [  0   0 255]
  [  0   0 255]
  ...
  [  0 255 255]
  [  0 255 255]
  [  0 255 255]]

 [[  0   0 255]
  [  0   0 255]
  [  0   0 255]
  ...
  [  0 255 255]
  [  0 255 255]
  [  0 255 255]]

 ...

 [[255   0   0]
  [255   0   0]
  [255   0   0]
  ...
  [  0 255   0]
  [  0 255   0]
  [  0 255   0]]

 [[255   0   0]
  [255   0   0]
  [255   0   0]
  ...
  [  0 255   0]
  [  0 255   0]
  [  0 255   0]]

 [[255   0   0]
  [255   0   0]
  [255   0   0]
  ...
  [  0 255   0]
  [  0 255   0]
  [  0 255   0]]]


>(5) 28*28 행렬(matrix) 형태로 픽셀 값을 출력해보고 출력 결과가 무엇을 보여주는지 답해보자.

In [ ]:
for i in range(28):
  for j in range(28):
    print("%3d" %color[i, j, 0], end="") # B 값을 저장
  print() # 줄바꿈

  0  0  0  0  0  0  0  0  0  0  0  0  0  0  0  0  0  0  0  0  0  0  0  0  0  0  0  0
  0  0  0  0  0  0  0  0  0  0  0  0  0  0  0  0  0  0  0  0  0  0  0  0  0  0  0  0
  0  0  0  0  0  0  0  0  0  0  0  0  0  0  0  0  0  0  0  0  0  0  0  0  0  0  0  0
  0  0  0  0  0  0  0  0  0  0  0  0  0  0  0  0  0  0  0  0  0  0  0  0  0  0  0  0
  0  0  0  0  0  0  0  0  0  0  0  0  0  0  0  0  0  0  0  0  0  0  0  0  0  0  0  0
  0  0  0  0  0  0  0  0  0  0  0  0  0  0  0  0  0  0  0  0  0  0  0  0  0  0  0  0
  0  0  0  0  0  0  0  0  0  0  0  0  0  0  0  0  0  0  0  0  0  0  0  0  0  0  0  0
  0  0  0  0  0  0  0  0  0  0  0  0  0  0  0  0  0  0  0  0  0  0  0  0  0  0  0  0
  0  0  0  0  0  0  0  0  0  0  0  0  0  0  0  0  0  0  0  0  0  0  0  0  0  0  0  0
  0  0  0  0  0  0  0  0  0  0  0  0  0  0  0  0  0  0  0  0  0  0  0  0  0  0  0  0
  0  0  0  0  0  0  0  0  0  0  0  0  0  0  0  0  0  0  0  0  0  0  0  0  0  0  0  0
  0  0  0  0  0  0  0  0  0  0  0  0  0  0  0  0  0  0  0  0  0  

> (6) 그린채널을 출력해보자.

In [ ]:
for i in range(28):
  for j in range(28):
    print("%3d" %color[i, j, 1], end="") # G 값을 저장
  print() # 줄바꿈

  0  0  0  0  0  0  0  0  0  0  0  0  0  0255255255255255255255255255255255255255255
  0  0  0  0  0  0  0  0  0  0  0  0  0  0255255255255255255255255255255255255255255
  0  0  0  0  0  0  0  0  0  0  0  0  0  0255255255255255255255255255255255255255255
  0  0  0  0  0  0  0  0  0  0  0  0  0  0255255255255255255255255255255255255255255
  0  0  0  0  0  0  0  0  0  0  0  0  0  0255255255255255255255255255255255255255255
  0  0  0  0  0  0  0  0  0  0  0  0  0  0255255255255255255255255255255255255255255
  0  0  0  0  0  0  0  0  0  0  0  0  0  0255255255255255255255255255255255255255255
  0  0  0  0  0  0  0  0  0  0  0  0  0  0255255255255255255255255255255255255255255
  0  0  0  0  0  0  0  0  0  0  0  0  0  0255255255255255255255255255255255255255255
  0  0  0  0  0  0  0  0  0  0  0  0  0  0255255255255255255255255255255255255255255
  0  0  0  0  0  0  0  0  0  0  0  0  0  0255255255255255255255255255255255255255255
  0  0  0  0  0  0  0  0  0  0  0  0  0  025525525525525525525525

> (7) 레드채널을 출력해보자.

In [ ]:
for i in range(28):
  for j in range(28):
    print("%3d" %color[i, j, 2], end="") # B 값을 저장
  print() # 줄바꿈

255255255255255255255255255255255255255255255255255255255255255255255255255255255255
255255255255255255255255255255255255255255255255255255255255255255255255255255255255
255255255255255255255255255255255255255255255255255255255255255255255255255255255255
255255255255255255255255255255255255255255255255255255255255255255255255255255255255
255255255255255255255255255255255255255255255255255255255255255255255255255255255255
255255255255255255255255255255255255255255255255255255255255255255255255255255255255
255255255255255255255255255255255255255255255255255255255255255255255255255255255255
255255255255255255255255255255255255255255255255255255255255255255255255255255255255
255255255255255255255255255255255255255255255255255255255255255255255255255255255255
255255255255255255255255255255255255255255255255255255255255255255255255255255255255
255255255255255255255255255255255255255255255255255255255255255255255255255255255255
25525525525525525525525525525525525525525525525525525525525525525