<a href="https://colab.research.google.com/github/KimSiGyum/Python/blob/main/3O4O5_%EA%B9%80%EC%8B%9C%EA%B2%B8_Numpy(%ED%95%99%EC%83%9D%EC%9A%A9).ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

#**🌈 Numpy(넘파이)**
- 공식사이트 : https://numpy.org/
- 참고문서 : https://numpy.org/doc/
---


###**▶ Numpy란?**


- Numerical Python의 줄임말
- 수치 해석과 계산 과학을 위한 파이썬 패키지
- 강력한 다차원 배열 자료구조인 넘파이 배열과 다양한 수치 계산 도구를 지원함

> <img src='https://drive.google.com/uc?id=1rBeII8xjrrl7e4cRbnIpO728UokopexW'>


###**▶ 넘파이 배열 (ndarray)**

- 다차원 배열을 구현한 자료구조 클래스
- C언어 배열로 구현되어 연산 속도가 빠르고 메모리 효율적임
- ndarray 객체는 같은 자료형의 원소만 저장할 수 있음(homogeneous array)
- ndarray 객체는 원소의 개수를 바꿀 수 없음(fixed-size items)
> <img src='https://drive.google.com/uc?id=1L1-8hdN3Reo7AVoVANgCLPkd1Gn1Sc3H' height=280>

#### **리스트의 불편한 점**

▷ 리스트 생성하기
>mid, fin은 각각 중간고사와 기말고사의 국영수 성적을 저장한 리스트이다.

In [ ]:
mid = [70, 80, 90]  # 중간고사 국,영,수 성적
fin = [80, 90, 100] # 기말고사 국,영,수 성적
mid_arr = np.array(mid)

▷ 리스트의 모든 값 수정하기
>중간고사의 국영수 성적을 5점씩 증가시켜보자.

In [ ]:
for i in range(len(mid)):
    mid[i] += 5
print(mid)

[75, 85, 95]


>아래와 같은 방법으로 국영수 성적을 모두 5씩 증가시킬 수 있을까?

In [ ]:
mid + 5
print(mid)

TypeError: can only concatenate list (not "int") to list

▷ 리스트끼리 더하기
>과목별 중간고사와 기말고사 점수를 합산해 새로운 리스트 tot에 저장해보자.

In [ ]:
tot = []
for i in range(3):
    tot.append(mid[i] + fin[i])
print(tot)

[150, 170, 190]


>아래와 같은 방법으로 국영수 성적을 모두 5씩 증가시킬 수 있을까?

In [ ]:
tot = mid + fin
tot

[70, 80, 90, 80, 90, 100]

#### **넘파이 배열의 편리한 점**

▷ 넘파이 배열 만들기

In [ ]:
# 넘파이 패키지 임포트하기
import numpy as np

In [ ]:
# 리스트를 넘파이 배열로 변환하기
mid_arr = np.array(mid)
fin_arr = np.array(fin)

In [ ]:
# 생성한 넘파이 배열 mid_arr 확인하기
mid_arr

array([70, 80, 90])

▷ 넘파이 배열의 모든 값 수정하기
>❗넘파이 배열과 스칼라(값)를 연산하면 반복문 없이도 모든 원소에 연산이 적용된다. (브로드캐스트)

In [ ]:
# 넘파이 배열 mid_arr의 모든 원소 5씩 증가시키기
mid_arr = mid_arr + 5
mid_arr

array([75, 85, 95])

▷ 넘파이 배열끼리 더하기
>❗반복문 없이 넘파이 배열 간 같은 인덱스의 원소끼리 연산을 수행할 수 있다. (벡터화 연산)

In [ ]:
# 두 넘파이 배열 mid_arr와 fin_arr의 합을 tot_arr에 저장하기
tot_arr = mid_arr + fin_arr
tot_arr

array([155, 175, 195])

#### **넘파이 배열 생성하기**

In [ ]:
import numpy as np

▷ array() : 리스트로 배열 만들기

In [ ]:
vector = np.array([1,2,3])
vector

array([1, 2, 3])

In [ ]:
matrix = np.array([[1,2,3], [4,5,6]])
matrix

array([[1, 2, 3],
       [4, 5, 6]])

In [ ]:
tensor = np.array([[[1,2,3], [4,5,6]], [[11,12,13], [14,15,16]]])
tensor

array([[[ 1,  2,  3],
        [ 4,  5,  6]],

       [[11, 12, 13],
        [14, 15, 16]]])

▷ arange() 함수 : 등차수열로 배열 만들기

In [ ]:
arr1 = np.arange(0, 15, 2)
arr1

array([ 0,  2,  4,  6,  8, 10, 12, 14])

▷ reshape() 함수 : 배열 형태 바꾸기

In [ ]:
arr2 = np.reshape(arr1, (2,4))# arr1을 2행 4열의 2차원 배열로 변환(함수이용)
arr2

array([[ 0,  2,  4,  6],
       [ 8, 10, 12, 14]])

In [ ]:
arr2m = arr1.reshape((2,4))# arr1을 2행 4열의 2차원 배열로 변환(메서드이용)
arr2m

array([[ 0,  2,  4,  6],
       [ 8, 10, 12, 14]])

▷ zeros(), ones() 함수 : 0 또는 1로 채워진 배열 만들기

In [ ]:
arr3 = np.zeros((3, 3), int)   #np.zeros((3, 3))
arr3

array([[0, 0, 0],
       [0, 0, 0],
       [0, 0, 0]])

In [ ]:
arr4 = np.ones((3,5))
arr4

array([[1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.]])

#### **넘파이 배열 속성**


>아래 코드를 실행해보고 넘파이 배열 속성 shape, ndim, size, dtype이 어떤 값인지 알아보자.

In [ ]:
print(vector.shape)
print(matrix.shape)
print(tensor.shape)

(3,)
(2, 3)
(2, 2, 3)


In [ ]:
print(vector.ndim)
print(matrix.ndim)
print(tensor.ndim)

1
2
3


In [ ]:
print(vector.size)
print(matrix.size)
print(tensor.size)

3
6
12


In [ ]:
print(vector.dtype)
print(matrix.dtype)
print(tensor.dtype)

int64
int64
int64


#### **넘파이 배열 인덱싱과 슬라이싱**


> <img src='https://drive.google.com/uc?id=1L1-8hdN3Reo7AVoVANgCLPkd1Gn1Sc3H' height=280>

▷ 인덱싱(indexing)
>위 그림의 넘파이 배열에서 숫자 2의 위치를 인덱싱 해보자.

In [ ]:
# vector에서 2 위치 인덱싱
vector[1]

2

In [ ]:
# vector에서 2 위치 인덱싱
vector[-2]

2

In [ ]:
# matrix에서 2 위치 인덱싱
matrix[0,1] #matrix[0][1] 속도 느림

2

In [ ]:
# tensor에서 2 위치 인덱싱
tensor[0,0,1]

2

▷ 슬라이싱(slicing)
>위 그림을 참고하여 다음 문장의 실행 결과를 예측해보자.

In [ ]:
vector[0:2]

array([1, 2])

In [ ]:
vector[0:1]

array([1])

In [ ]:
vector[:1]

array([1])

In [ ]:
vector[0] # 인덱싱과 슬라이싱의 차이점 확인

1

In [ ]:
vector[1:]

array([2, 3])

In [ ]:
vector[:]

array([1, 2, 3])

In [ ]:
matrix[:1, :1]

array([[1]])

In [ ]:
matrix[:, :1]

array([[1],
       [4]])

In [ ]:
tensor[:, :1, :1]

array([[[ 1]],

       [[11]]])

###**▶ 연습문제**

---
**응용문제 :** 넘파이 배열 mid_arr의 모든 원소를 3배하여 넘파이 배열 score에 저장하고 출력해보자.

---

In [ ]:
score = mid_arr * 3
score

array([210, 240, 270])

---
**응용문제 :** 원소가 0부터 시작해 1씩 증가하는 3*3 형태의 넘파이 배열을 만들어보자.

---

In [ ]:
np.arange(9).reshape((3,3))

array([[0, 1, 2],
       [3, 4, 5],
       [6, 7, 8]])

In [ ]:
np.reshape(np.arange(9), (3,3))

array([[0, 1, 2],
       [3, 4, 5],
       [6, 7, 8]])

---
**응용문제 :** 위에서 생성한 넘파이 배열의 형태를 확인해보자.

---

In [ ]:
print(score.shape)
print(arr3.shape)

(3,)
(3, 3)
